---
version: 5.8.0
slug: configurator
name: File editor
description: Simple browser-based file editor for Home Assistant
url: https://github.com/home-assistant/addons/tree/master/configurator
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
homeassistant: 0.91.1
homeassistant_api: true
image: homeassistant/{arch}-addon-configurator
ingress: true
init: false
map:
  - all_addon_configs:rw
  - backup:rw
  - homeassistant_config:rw
  - media:rw
  - share:rw
  - ssl:rw
options:
  dirsfirst: false
  enforce_basepath: true
  git: true
  ignore_pattern:
    - __pycache__
    - .cloud
    - .storage
    - deps
  ssh_keys: []
panel_icon: mdi:wrench
schema:
  dirsfirst: bool
  enforce_basepath: bool
  git: bool
  ignore_pattern:
    - str
  ssh_keys:
    - str
    modbus:
  - name: alphaess
    type: tcp
    host: 192.168.68.144
    port: 502
    unit_id: 1
    timeout: 5
    sensor:
  - platform: modbus
    scan_interval: 10
    registers:
      - name: "AlphaESS Battery SOC (test)"
        hub: alphaess
        unit_of_measurement: "%"
        address: 33022
        input_type: holding
        data_type: uint16
        scale: 0.1
